### PR TITLE
Replace link helpers with link class helpers

### LINKED ISSUE #193: `govuk_link_to` misbehaves when given url_options without any html_options.
When `govuk_link_to` is called with url_options hash (https://apidock.com/rails/ActionView/Helpers/UrlHelper/link_to) it appends class to url_options instead of html_options, resulting in link without `govuk-link` class and with href with appended `?class=govuk-link`.

```
    <%= govuk_link_to "show", action: :show %>  #=> <a href="{correct_url}?class=govuk-link">
```
This can be avoided by adding `button: false` and parenthesising url_options:

```
    <%= govuk_link_to "show", { action: :show }, button: false %>  #=> <a class="govuk-link" href="{correct_url}">
```

Parenthesising alone does not fix the issue - url_options are then still treated as kwargs rather than part of *args (which I find a bit odd - this might depend on ruby version though)

### PR DESCRIPTION
**Pull request by peteryates**
Wrapping Rails' `#link_to`, `#mail_to` and `#button_to` helpers is difficult because of the internal implementation and the complications added by mixing keyword arguments in with the existing args. This difficulty is exacerbated by the change in [Ruby 3.0's separation of positional and keyword args](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/).

The above problems have been highlighted a couple of times (#66, #193) and have probably bitten other teams/developers more often.

This approach no longer attempts to wrap the methods directly but instead provides a easier way of building the GOV.UK-specific classes.

Instead of:

```slim
= govuk_link_to "some page", some_path, muted: true
```

We would now do:

```slim
= link_to "some page", some_path, class: govuk_link_classes(muted: true)
```

The `#govuk_link_classes` helper supports all the CSS options from govuk-frontend, including `:no_visited_state`, `:muted`, `:text_colour`, `:inverse`, and `:no_underline`.

The `#govuk_button_classes` helper supports `:warning`, `:disabled` and `:secondary` button styles.

Benefits of this approach:

* no complex code that juggles with arguments, optional arguments and different keyword arg handling across various versions of Ruby
* I actually understand it
* we can easily apply the styles to Rails' other link helpers, like #link_to_if, #link_to_unless and friends.

Fixes #193

### CODE REVIEW

**Comment by frankieroberto** [comment]
Like this idea!

Rather than a bunch of boolean arguments, would it make sense for `govuk_link_classes()` to accept an array of symbols instead? ie

```ruby
govuk_link_classes(:muted, :no_visited_state)
```

That way we could also allow you to add on your own classes as strings:

```ruby
govuk_link_classes(:muted, :no_visited_state, "app-link--super-important")
```

to avoid having to do this:

```ruby
link_to "blah", "/", class: govuk_link_classes(:muted, :no_visited_state).push("app-link--super-important")
```

**Comment by edwardhorsford** [comment]
I might be wary of this - as I think it makes it more likely that developers would forget it.

it's quite common for developers to attempt to style things as buttons or links using the classes alone - my hunch would be that having a named `govuk` thing to use helps reinforce that most things should be using `govuk` versions rather than native.

**Comment by cpjmcquillan** [comment]
I'd also throw in my 2p that... 
```ruby
link_to "something", "#here", class: govuk_link_classes(:some_option)
```

Doesn't feel much different to...
```ruby
link_to "something", "#here", class: "all-the classes-i want-to add govuk-link"
```

I'd be wary of the few instances where the existing helper isn't suitable driving a fairly significant change to something that is really useful to lots of teams in the vast majority of use cases!

**Comment by peteryates** [comment]
Thanks for the feedback all.

@BroiSatse has made an excellent attempt at implementing a version of `#govuk_link_to` that does the necessary argument juggling (#197) and I think the two can live side-by-side, ideally with the link helpers using the class helpers.

Going to see if I can combine the to approaches into one PR. Also using symbols seems like a good idea, will look into that too 💡

**Comment by peteryates** [comment]
Ok, so this PR took a little detour but now we have:

* new link and button class helpers that can be injected into any of Rails myriad of link helpers
* re-written wrappers for `#link_to`, `#button_to` and `#mail_to` that properly add the GOV.UK classes without (hopefully, at least) affecting the underlying Rails functionality. Many thanks to @BroiSatse for his help on this

**Pull request merged**
